config/routes.rb
GmEcomm::Application.routes.draw do

  
  
 

  get "gmuser_sessions/new"

  
  

  

  resources :api
  match '/api/create_user' => 'api#create_user'
  
resources :users, :user_sessions
 match 'logout' => 'user_sessions#destroy', :as => :logout  
  match 'login' => 'user_sessions#new', :as => :login
  
resources :retailers, :retaileradmin_sessions
  match 'signin' => 'retaileradmin_sessions#new', :as => :signin
  match 'signout' => 'retaileradmin_sessions#destroy', :as => :signout
  match '/new_request_form' => 'retailers#new_request_form'
  match '/notify_gm' => 'retailers#notify_gm'
  
resources :malladms, :malladmin_sessions
  match 'mallmanagersignin' => 'malladmin_sessions#new', :as => :mallmanagersignin
  match 'mallmanagersignout' => 'malladmin_sessions#destroy', :as => :mallmanagersignout
  match '/new_request_gm' => 'malladms#new_request_gm'
  match '/request_gm' => 'malladms#request_gm'
  
resources :gmusers, :gmuser_sessions
  match '/gmusersignin' => 'gmuser_sessions#new', :as => :gmusersignin
  match '/gmusersignout' => 'gmuser_sessions#destroy', :as => :gmusersignout
  match '/gmusersignup' => 'gmusers#new', :as => :gmusersignup  
  
resources :admin
resources :products
resources :malls
resources :lifestyles
resources :retailers        
resources :retaileradmins 
resources :malladms
resources :malladmins
      
      match '/productslist' => 'home#productslist'
      match '/lifestyleslist' => 'lifestyles#lifestyleslist'
      match '/products_index' => 'lifestyles#product_index'
      match '/check_product' => 'lifestyles#check_product'
      match '/search' => 'products#search', :as => :search
   
  root :to => "home#index"

end

app/models/gmuser.rb
class Gmuser < ActiveRecord::Base
  
   acts_as_authentic do |c|
    c.validate_email_field = false
    end
  
  
#  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
#  
#  validates :username,  :presence => true, :length => { :maximum => 30 }, :uniqueness => true
#  validates :email, :presence => true, 
#                    :format => {:with => email_regex},
#                    :uniqueness => true
#  
#  validates :password, :presence => true,
#                       :confirmation => true,
#                       :length => { :within => 6..20 }
end

app/models/gmuser_session.rb
class GmuserSession < Authlogic::Session::Base
   
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/models/lifestyle.rb
class Lifestyle < ActiveRecord::Base
  
  belongs_to :product
  
end

app/models/mall.rb
class Mall < ActiveRecord::Base
end

app/models/malladm.rb
class Malladm < ActiveRecord::Base
   
   attr_accessor :password 
   attr_accessible :username, :password
  
  acts_as_authentic do |config|
# Add custom configuration options here.
  config.crypto_provider = Authlogic::CryptoProviders::MD5
  end
  
   
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username,  :presence => true, :length => { :maximum => 30 }, :uniqueness => true
  validates :email, :presence => true, 
                    :format => {:with => email_regex},
                    :uniqueness => true
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
end

app/models/malladmin.rb
class Malladmin < ActiveRecord::Base
  
  acts_as_authentic do |c|
    c.validate_email_field = false
    end
    
   
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username,  :presence => true, :length => { :maximum => 30 }, :uniqueness => true
  validates :email, :presence => true, 
                    :format => {:with => email_regex},
                    :uniqueness => true
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
  
end

app/models/mallmanager.rb
class Mallmanageradmin < ActiveRecord::Base
  
  acts_as_authentic do |c|
    c.validate_email_field = false
    end
  
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username,  :presence => true, :length => { :maximum => 30 }, :uniqueness => true
  validates :email, :presence => true, 
                    :format => {:with => email_regex},
                    :uniqueness => true
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
  
end

app/models/mapview.rb
class Mapview < ActiveRecord::Base


end

app/models/product.rb
class Product < ActiveRecord::Base

   has_attached_file :image, :styles => {:thumb => "50x50"}
   
   has_one :lifestyle
   
  validates :name, :uniqueness => true, :presence => true, :length => {:maximum => 20}
  validates :description, :presence => true, :length => {:maximum => 160}
  validates :image, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :discount, :numericality => {:greater_than_or_equal_to => 0.0}
  #validates :image, :format => { :with => %r{\.(gif|jpg|png)$}}

end

app/models/retailer.rb
#this file is not in use of current application

class Retailer < ActiveRecord::Base
  
   #attr_accessor :password 
   #attr_accessible :username, :password
  
   acts_as_authentic do |c|
    c.validate_email_field = false
    end
  

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username,  :presence => true, :length => { :maximum => 30 }, :uniqueness => true
  validates :email, :presence => true, 
                    :format => {:with => email_regex},
                    :uniqueness => true
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
  
  
end

app/models/retaileradmin.rb
class Retaileradmin < ActiveRecord::Base
  #attr_accessor :password, :password_confirmation
  
  #attr_accessible :username, :password, :password_confirmation, :email
  
  #before_save :encrypt_password
  
   acts_as_authentic do |c|
    c.validate_email_field = false
    end
  
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username,  :presence => true, :length => { :maximum => 30 }, :uniqueness => true
  validates :email, :presence => true, 
                    :format => {:with => email_regex},
                    :uniqueness => true
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
     
  
  
end

app/models/user.rb
class User < ActiveRecord::Base

   #attr_accessor :password 
   
   #attr_accessible :username, :password, :password_confirmation
   
   acts_as_authentic do |c|
    c.validate_email_field = false
    end

  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username,  :presence => true, :length => { :maximum => 30 }, :uniqueness => true
  validates :email, :presence => true, 
                    :format => {:with => email_regex},
                    :uniqueness => true
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  #attr_accessor :password, :roll
  
  #attr_accessor :username, :password, :password_confirmation, :roll
  
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/gmusers_helper.rb
module GmusersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/malladms_helper.rb
module MalladmsHelper
end

app/helpers/malls_helper.rb
module MallsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<script type="text/javascript">
  
   var lastMenu = "start";

  function togglekeyboard(){
    var ele = document.getElementById("virtkey") ;
    if(ele.style.display == "none"){
      ele.style.display = "block";
      document.getElementById("keytoggle").innerHTML = "Hide Keyboard";
    }
    else {
      ele.style.display = "none";
      document.getElementById("keytoggle").innerHTML = "Show Keyboard";
    } 
  }  
  
  function toggleMenu(element){
        if (lastMenu == "start"){
                doSlide(element);
                lastMenu = element;
            }    
        else if(lastMenu == element){
            doSlide(element);
            lastMenu = "start";
            }
        else{
            doSlide(lastMenu);    
            doSlide(element);
            lastMenu = element;
            }    

}

    function doSlide(id){
      opac =0.0;	
      timeToSlide = 40; // in milliseconds
      obj = document.getElementById(id);
      if(obj.style.display == "none"){ // if it's already hidden we slide it down
        obj.style.visibility = "hidden";
        obj.style.display = "block";
        height = obj.offsetHeight;
        obj.style.height="0px";
        obj.style.visibility = "visible";
        slideDown(0,obj,0,height,Math.ceil(height/timeToSlide));
      } else {
        slideUp(1,obj,Math.ceil(obj.offsetHeight/timeToSlide),obj.offsetHeight);
      }
    }
	 
    function slideDown(opac,obj,offset,full,px){
	
      if(offset < full){
        mx = 0.04
        obj.style.height = offset+"px";
        offset=offset+px;
        obj.style.opacity = opac;
        opac=opac+mx;
        setTimeout((function(){slideDown(opac,obj,offset,full,px);}),1);
      } else {
        obj.style.height = full+"px"; //If the data inside is updated on runtime you can use auto instead...
      }
    }
	 
    function slideUp(opac,obj,px,full){
      if((obj.offsetHeight-px) > 0){
        mx = 0.0125
        obj.style.height = obj.offsetHeight-px+"px";
        obj.style.opacity = opac;
        opac=opac-mx;
        setTimeout((function(){slideUp(opac,obj,px,full);}),1);
      } else {
        obj.style.height=full+"px"; // we reset the height if we were to slide it back down
        obj.style.display = 'none';
      }
    }

</script>

    <div style="color: black; background-color:white; height: 100%"> 
    	<div class="top-links" ></div>	
    		
        <h1>Admin Dashboard</h1>
        <br/>

        <div class="admin-pannel">
        <table width="100%" height="965px" cellpadding="0">
          <tr>
            <td class="admin-left" valign="top" >
              <div class= "admin-button">
              	<ul>
                <div class="ad-title">
                  <a href="javascript:void(0);"  onclick="toggleMenu('product-menu');" ><h3>Products</h3></a>
                    <li id="product-menu" style="display :none;" class="ad-title-sub" >
                      <ul class="sub-link">
                          <%= link_to 'Add Products', new_product_url, :remote => true %>
                                                    
                          <%= link_to 'Modify Products', products_url, :remote => true %>
                     </ul>
                    </li> 
                </div>
                <div class="ad-title">
                  <a href="javascript:void(0);"  onclick="toggleMenu('retailer-menu');" ><h3>Retailers</h3></a>
                     <li id="retailer-menu" style="display :none;" class="ad-title-sub" >
                       <ul class="sub-link">
                          <%= link_to 'Add Retailer', new_retaileradmin_url, :remote => true %>
                                                    
                          <%= link_to 'Modify Retailer', retaileradmins_url, :remote => true %>
                       </ul>
                     </li>
              	</ul>
             </div> 
                  <div class="ad-title">
                  <a href="javascript:void(0);"  onclick="toggleMenu('mallmanager-menu');" ><h3>Mall Managers</h3></a>
                    <li id="mallmanager-menu" style="display :none;" class="ad-title-sub" >
                      <ul class="sub-link">
                          <%= link_to 'Add Mall Managers', new_malladmin_url, :remote => true %>
                                                    
                          <%= link_to 'Modify Mall Managers', malladmins_url, :remote => true %>
                     </ul>
                    </li> 
                </div>
            </td>
            <td valign="top" class="admin-right">  
            <div id="virtkey" style="display: none; position: absolute; right: 28px; z-index: 3;">
                    <iframe src="http://www.virtualkeyboard.ws/plugin.shtml" frameborder="0" marginheight="0" marginwidth="0" scrolling="no" width="350" height="280" style="border:thin outset">
                         Free virtual keyboard plugin from <a href="http://www.virtualkeyboard.ws" target="_blank">virtualkeyboard.ws</a>
                    </iframe>
                  </div>
              <div>
                    <a herf="javascript:void(0)" onclick="togglekeyboard()">
                      <div id="keytoggle"> Keyboard </div>
                    </a>
                  </div>
              <div id="right_col">
              </div>
            </td>
          </tr>
        </table>
        </div>
</div>

</ul>
        </div>
             
           


                 

app/views/notifier/email_to_gm.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<h1>Welcome to GM Retail Marketing</h1>
<h2>About Your Business</h2>
<p>Type of business: <%= "#{@businesstype}" %></p>
  <p>Name of business: <%= "#{@businessname}" %></p>
    <p>City: <%= "#{@city}" %></p>
    <p>State: <%= "#{@state}" %></p>
    <p>Street address: <%= "#{@streetaddress}" %></p>
    <p>Zipcode: <%= "#{@zipcode}" %></p>
  <p>-----------------------------------------------------------------------------------------</p>  
    <h2>Your Info</h2>
    <p>Your full name:: <%= "#{@fullname}" %></p>
    <p>Your email address: <%= "#{@email}" %></p>
    <p>Your phone number: <%= "#{@phonenumber}" %></p>   
    <p>Upload a photo of your business :</p>
    <p>Inside: <%= "#{@inside}" %></p>
    <p>Outside: <%= "#{@outside}" %></p>
    <p>Website: <%= "#{@website}" %></p>
 <p>-----------------------------------------------------------------------------------------</p>   
    <h2>Product Info</h2>
    <p>Product Name: <%= "#{@name}" %></p>
    <p>Product Description: <%= "#{@description}" %></p>
    <p>Product Image: <%= "#{@image}"%></p>
    <p>Product Price: <%= "#{@price}" %></p>
    <p>Message: <%= "#{@message}"%></p>
<p>Thanks for sending a mail</p>
</body>
</html>

app/views/notifier/email_to_gm.text.erb
<%= @greeting %> thanks! It's only testing purpose
<p>Name:<%= @name %></p>
<p>Description:<%= @description %></p>
<p>Price:<%= @price%></p>

app/views/notifier/mallmanageremail_to_gm.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<h1>Welcome to GM Retail Marketing</h1>
   <h2>Your Info</h2>
    <p>Your full name:: <%= "#{@fullname}" %></p>
    <p>Your email address: <%= "#{@email}" %></p>
    <p>Your phone number: <%= "#{@phonenumber}" %></p>   
    <p>City: <%= "#{@city}" %></p>
    <p>State: <%= "#{@state}" %></p>
    <p>Street address: <%= "#{@streetaddress}" %></p>
    <p>Zipcode: <%= "#{@zipcode}" %></p>
  <p>-----------------------------------------------------------------------------------------</p>  
    <p>Upload a photo of your business :</p>
    <p>Inside: <%= "#{@inside}" %></p>
    <p>Outside: <%= "#{@outside}" %></p>
    <p>Website: <%= "#{@website}" %></p>
 <p>-----------------------------------------------------------------------------------------</p>   
    <p>Message: <%= "#{@message}"%></p>
<p>Thanks for sending a mail</p>
</body>
</html>

app/views/notifier/mallmanageremail_to_gm.text.erb
<%= @greeting %> thanks! It's only testing purpose
<p>Name:<%= @name %></p>
<p>Description:<%= @description %></p>
<p>Price:<%= @price%></p>