config/routes.rb
GmEcomm::Application.routes.draw do

  
  
 

  get "gmuser_sessions/new"

  
  

  

  resources :api
  match '/api/create_user' => 'api#create_user'
  
resources :users, :user_sessions
 match 'logout' => 'user_sessions#destroy', :as => :logout  
  match 'login' => 'user_sessions#new', :as => :login
  
resources :retailers, :retaileradmin_sessions
  match 'signin' => 'retaileradmin_sessions#new', :as => :signin
  match 'signout' => 'retaileradmin_sessions#destroy', :as => :signout
  match '/new_request_form' => 'retailers#new_request_form'
  match '/notify_gm' => 'retailers#notify_gm'
  
resources :malladms, :malladmin_sessions
  match 'mallmanagersignin' => 'malladmin_sessions#new', :as => :mallmanagersignin
  match 'mallmanagersignout' => 'malladmin_sessions#destroy', :as => :mallmanagersignout
  match '/new_request_gm' => 'malladms#new_request_gm'
  match '/request_gm' => 'malladms#request_gm'
  
resources :gmusers, :gmuser_sessions
  match '/gmusersignin' => 'gmuser_sessions#new', :as => :gmusersignin
  match '/gmusersignout' => 'gmuser_sessions#destroy', :as => :gmusersignout
  match '/gmusersignup' => 'gmusers#new', :as => :gmusersignup  
  
resources :admin
resources :products
resources :malls
resources :lifestyles
resources :retailers        
resources :retaileradmins 
resources :malladms
resources :malladmins
      
      match '/productslist' => 'home#productslist'
      match '/lifestyleslist' => 'lifestyles#lifestyleslist'
      match '/products_index' => 'lifestyles#product_index'
      match '/check_product' => 'lifestyles#check_product'
      match '/search' => 'products#search', :as => :search
   
  root :to => "home#index"

end

app/models/retailer.rb
#this file is not in use of current application

class Retailer < ActiveRecord::Base
  
   #attr_accessor :password 
   #attr_accessible :username, :password
  
   acts_as_authentic do |c|
    c.validate_email_field = false
    end
  

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username,  :presence => true, :length => { :maximum => 30 }, :uniqueness => true
  validates :email, :presence => true, 
                    :format => {:with => email_regex},
                    :uniqueness => true
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
  
  
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
 layout 'user'
 
  before_filter :authenticate
 
 
  def index
          
  end
  
   def edit
    @retaileradmin = Retaileradmin.find(params[:id])
    #@retaileradmins = Retaileradmin.all
    respond_to do |format|
      format.js
    end
  end
  
    def update
    @retaileradmin = Retaileradmin.find(params[:id])
      if @retaileradmin.update_attributes(params[:retaileradmin])
        flash[:notice] = 'Retaileradmin was successfully updated.'
        @retaileradmins = Retaileradmin.all
        responds_to_parent do |format|
          flash[:notice] = 'Retaileradmin was successfully updated.'
          render :action => 'new_request_form'
        end
      else
        responds_to_parent do 
           flash[:notice] = "There was an error while updating the Retailer information."
           render :action => 'edit'
      end
    end
  end
  
  
  def new_request_form
    
  end
  
  def notify_gm
    Notifier.email_to_gm(params[:businesstype],params[:businessname], params[:city], params[:state], params[:streetaddress], params[:zipcode],params[:fullname], params[:email], params[:phonenumber], params[:inside], params[:outside], params[:website], params[:name], params[:description], params[:image], params[:price], params[:message]).deliver
    flash.now[:notice] = "Successfully sent a message to Gm."
    render :action => 'index'
    
  end
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/retailers/_edit.html.erb
<div style="height: 894px; overflow: scroll;">
<%= form_for(@retaileradmin, :validate => true, :url => retailer_path + ".js", :html => {:multipart => true, :target => 'frame'} ) do |f| %>
   <% if @retaileradmin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retaileradmin.errors.count, "error") %> prohibited this retaileradmin from being saved:</h2>

      <ul>
      <% @retaileradmin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :confirm_password %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%#= f.label :persistence_token %><br />
    <%#= f.text_field :persistence_token %>
  </div>
  
    <%= f.submit "Update" %>
  
<% end %>
<iframe id='frame' name="frame" style="width:1px;height:1px; border:0px" src="about:blank"></iframe>
</div>

app/views/retailers/_new_request_form.html.erb
<div style="height: 894px; overflow: scroll;">

<%= form_tag '/notify_gm', :url => retailers_path + ".js", :html => {:multipart => true, :target => 'frame'} do |f| %>
<table>
	<tr>
        <h2>About Your Business</h2>
		<p>Type of business:<br></p>
		<p><%= text_field_tag :businesstype %></p>
		
		<p>Name of business:<br></p>
		<p><%= text_field_tag :businessname %></p>
				
		<p>City:<br></p>
		<p><%= text_field_tag :city %></p>
		
		<p>State:<br></p>
		<p><%= text_field_tag :state %></p>
		
		<p>Street address:<br></p>
		<p><%= text_field_tag :streetaddress %></p>
		
		<p>ZIP code:<br></p>
		<p><%= text_field_tag :zipcode %></p>
		</tr>
		<p>-----------------------------------------------------------------------------------------</p>
	<tr>
        <h2>Your Info</h2>
		
		<p>Your full name:<br></p>
		<p><%= text_field_tag :fullname %></p>
		
        <p>Your email address:<br></p>
		<p><%= text_field_tag :email %></p>
		
		<p>Your phone number:<br></p>
		<p><%= text_field_tag :phonenumber %></p>
        
        <p>Upload a photo of your business :<br></p>
		<p>inside: &nbsp;&nbsp;<%= file_field_tag :inside %></p>
		<p>outside: <%= file_field_tag :outside %></p>
		
		<p>Website or facebook address of your business</p>
		<p><%= text_field_tag :website %>		
		</tr>
		<p>-----------------------------------------------------------------------------------------</p>

		<tr>
        <h2>Product Info</h2>
			
		<p>Product Name:<br/></p>
		<p><%= text_field_tag :name %><br/></p>
		
      	<p>Product Description:</p></br>
      	<p><%= text_area_tag :description %></br></p>
      	
      	<p>Product Image:</p></br>
      	<p><%= file_field_tag :image %></br></p>
      	
    	<p>Product Price:</br></p>
    	<p><%= text_field_tag  :price %></p>
    	
    	<p>Message:</p></br>
      	<p><%= text_area_tag :message %></br></p>
        </tr>		
    

<%= submit_tag 'Submit' %>
<% end %>
         <iframe id='frame' name="frame" style="width:1px;height:1px; border:0px" src="about:blank"></iframe>
         <div/>

app/views/retailers/edit.js.erb
jQuery("#right_col").html("<%= escape_javascript(render(:partial => 'edit'))%>");

app/views/retailers/index.html.erb
<script type="text/javascript">
  
   var lastMenu = "start";

  function togglekeyboard(){
    var ele = document.getElementById("virtkey") ;
    if(ele.style.display == "none"){
      ele.style.display = "block";
      document.getElementById("keytoggle").innerHTML = "Hide Keyboard";
    }
    else {
      ele.style.display = "none";
      document.getElementById("keytoggle").innerHTML = "Show Keyboard";
    } 
  }  
  
  function toggleMenu(element){
        if (lastMenu == "start"){
                doSlide(element);
                lastMenu = element;
            }    
        else if(lastMenu == element){
            doSlide(element);
            lastMenu = "start";
            }
        else{
            doSlide(lastMenu);    
            doSlide(element);
            lastMenu = element;
            }    

}

    function doSlide(id){
      opac =0.0;	
      timeToSlide = 40; // in milliseconds
      obj = document.getElementById(id);
      if(obj.style.display == "none"){ // if it's already hidden we slide it down
        obj.style.visibility = "hidden";
        obj.style.display = "block";
        height = obj.offsetHeight;
        obj.style.height="0px";
        obj.style.visibility = "visible";
        slideDown(0,obj,0,height,Math.ceil(height/timeToSlide));
      } else {
        slideUp(1,obj,Math.ceil(obj.offsetHeight/timeToSlide),obj.offsetHeight);
      }
    }
	 
    function slideDown(opac,obj,offset,full,px){
	
      if(offset < full){
        mx = 0.04
        obj.style.height = offset+"px";
        offset=offset+px;
        obj.style.opacity = opac;
        opac=opac+mx;
        setTimeout((function(){slideDown(opac,obj,offset,full,px);}),1);
      } else {
        obj.style.height = full+"px"; //If the data inside is updated on runtime you can use auto instead...
      }
    }
	 
    function slideUp(opac,obj,px,full){
      if((obj.offsetHeight-px) > 0){
        mx = 0.0125
        obj.style.height = obj.offsetHeight-px+"px";
        obj.style.opacity = opac;
        opac=opac-mx;
        setTimeout((function(){slideUp(opac,obj,px,full);}),1);
      } else {
        obj.style.height=full+"px"; // we reset the height if we were to slide it back down
        obj.style.display = 'none';
      }
    }

</script>

<div style="color: black; background-color:white; height: 100%"> 
    	<div class="retailertop-links" > 
          <div class="retailer-liks-parent"> 
    <div class="retaileradmin-links">
  	     <% if current_retaileradmin %>
  	        <%# current_retaileradmin.username == "admin" %>
            
            <%= link_to "Edit Profile", edit_retailer_path(current_retaileradmin.id), :remote => true %>
            <%= link_to "Retailer", '/retailers', :class=>"a-link"%>     
            <%= link_to "Signout", :signout %> 
            
        <% else %>
        <!--%#= link_to "Register", new_user_path%-->
        <% end %>
         </div> 
       </div>
        </div>	
    		
        <h1>Retailer Dashboard</h1>
        <br/>

        <div class="admin-pannel">
        <table width="100%" height="965px" cellpadding="0">
          <tr>
            <td class="admin-left" valign="top">
              <div class= "admin-button">
              	<ul>
                <div class="ad-title">
                  <a href="javascript:void(0);"  onclick="toggleMenu('product-menu');" ><h3>Request to GM admin</h3></a>
                
                
                <li id="product-menu" style="display :none;" class="ad-title-sub" >
                    <ul class="sub-link">
                        
                          <%= link_to 'New Product Form', "new_request_form", :remote => true %>
                                                                             
                    </ul>
                </li>
              	</ul>
              	</div> 
              	 </td>
            <td valign="top" class="admin-right">  
            	 <div id="virtkey" style="    display: none; position: absolute; right: 78px; z-index: 3;">
                    <iframe src="http://www.virtualkeyboard.ws/plugin.shtml" frameborder="0" marginheight="0" marginwidth="0" scrolling="no" width="350" height="280" style="border:thin outset">
                         Free virtual keyboard plugin from <a href="http://www.virtualkeyboard.ws" target="_blank">virtualkeyboard.ws</a>
                    </iframe>
                  </div>
              <div>
                    <a herf="javascript:void(0)" onclick="togglekeyboard()">
                      <div id="keytoggle"> Keyboard </div>
                    </a>
                  </div>
              	<div id="right_col" >
              </div>
               </div>
            </td>
          </tr>
        </table>
        </div>
</div>

</ul>
        </div>
     

app/views/retailers/new_request_form.js.erb
$("#right_col").html("<%= escape_javascript(render(:partial => 'new_request_form'))%>");

app/views/retailers/notify_gm.html.erb
<% form_tag "/notify_gm", :method => :get do |f|% ->
  <table>
     <tr><div class="field">
     <h2>About Your Business</h2>
     </div>
        
     <div class="field">
     <p>Type of business:<br><%= text_field_tag :businesstype %></p>
     </div>
		
     <div class="field">
     <p>Name of business:<br><%= text_field_tag :businessname %></p>
      </div>
		
     <div class="field">		
     <p>City:<br><%= text_field_tag :city %></p>
     </div>
		
     <div class="field">
     <p>State:<br><%= text_field_tag :state %></p>
     </div>
		
     <div class="field">
     <p>Street address:<br><%= text_field_tag :streetaddress %></p>
     </div>

     <div class="field">
     <p>ZIP code:<br><%= text_field_tag :zipcode %></p>
     </div>
     </tr> 
     <div class="field">
     <%= f.label "name" %>: <%= text_field_tag :name %>
     </div>
     <div class="field">
     <%= f.label "description" %>: <%= text_area_tag :description %>
     </div>
     <div class="field">
     <%= f.label "price" %>: <%= text_field_tag :price %>
     </div>
     <div class="field">
     <%= f.label "image" %>:<%= file_field_tag :image %>
     </div>
     <div class="field">
     <%= f.label "message" %>: <%= text_area_tag :message %>
     </div>
     <div class="actions">
     <%= submit_tag "Send E-mail" %>
     </div>
 <% end %>