config/routes.rb
GmEcomm::Application.routes.draw do

  
  
 

  get "gmuser_sessions/new"

  
  

  

  resources :api
  match '/api/create_user' => 'api#create_user'
  
resources :users, :user_sessions
 match 'logout' => 'user_sessions#destroy', :as => :logout  
  match 'login' => 'user_sessions#new', :as => :login
  
resources :retailers, :retaileradmin_sessions
  match 'signin' => 'retaileradmin_sessions#new', :as => :signin
  match 'signout' => 'retaileradmin_sessions#destroy', :as => :signout
  match '/new_request_form' => 'retailers#new_request_form'
  match '/notify_gm' => 'retailers#notify_gm'
  
resources :malladms, :malladmin_sessions
  match 'mallmanagersignin' => 'malladmin_sessions#new', :as => :mallmanagersignin
  match 'mallmanagersignout' => 'malladmin_sessions#destroy', :as => :mallmanagersignout
  match '/new_request_gm' => 'malladms#new_request_gm'
  match '/request_gm' => 'malladms#request_gm'
  
resources :gmusers, :gmuser_sessions
  match '/gmusersignin' => 'gmuser_sessions#new', :as => :gmusersignin
  match '/gmusersignout' => 'gmuser_sessions#destroy', :as => :gmusersignout
  match '/gmusersignup' => 'gmusers#new', :as => :gmusersignup  
  
resources :admin
resources :products
resources :malls
resources :lifestyles
resources :retailers        
resources :retaileradmins 
resources :malladms
resources :malladmins
      
      match '/productslist' => 'home#productslist'
      match '/lifestyleslist' => 'lifestyles#lifestyleslist'
      match '/products_index' => 'lifestyles#product_index'
      match '/check_product' => 'lifestyles#check_product'
      match '/search' => 'products#search', :as => :search
   
  root :to => "home#index"

end

app/models/malladmin_session.rb
class MalladminSession < Authlogic::Session::Base
  def to_key
    #self.keys.to_a 
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
  
end

app/controllers/malladmin_sessions_controller.rb
class MalladminSessionsController < ApplicationController
  
  layout 'user'
 # before_filter :authenticate #, :only => :destroy
  
  #new session
  def new
    if current_malladmin
      
      redirect_to '/malladms'
    else
      @malladmin_session = MalladminSession.new
      respond_to do |format|
        format.html # new.html.erb
        format.xml { render :xml => @malladmin_session }
      end
    end
    
  end
  
  #create new session for retailer
  def create
    @malladmin_session = MalladminSession.new(params[:malladmin_session])
    respond_to do |format|
    if @malladmin_session.save
      format.html { redirect_to('/malladms' , :notice => 'Login Successful') }
        format.xml { render :xml => @malladmin_session, :status => :created, :location => @malladmin_session }
       else
        format.html { render :action => "new" }
        format.xml { render :xml => @malladmin_session.errors, :status => :unprocessable_entity }
    end
   end 
 end
        
   
  
  #destroy current session
  
  def destroy
    @mall_session = MalladminSession.find
    @mall_session.destroy

    respond_to do |format|
      format.html { redirect_to(root_url, :notice => 'Goodbye!') }
      format.xml { head :ok }
  end
 end
end

app/helpers/malladmin_sessions_helper.rb
module MalladminSessionsHelper
end

app/views/malladmin_sessions/_form.html.erb
<%= form_for(@malladmin_session) do |f| %>
  <% if @malladmin_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@malladmin_session.errors.count, "error") %> prohibited this malladmin_session from being saved:</h2>

      <ul>
      <% @malladmin_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div><br/>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <!--div class="field">
  	<%# ["Retailer", "Mall Manager"].each do |c| %>
  	<%#= f.radio_button :roll, c %><%#= c %>
  	<%# end %>  
  	</div--><br/>
  <div class="actions">
    <%= f.submit "Login" %>
    <!--input id="user_session_submit" type="submit" value="Login" name="commit"-->
  </div>
<% end %>

app/views/malladmin_sessions/edit.html.erb
<h1>Editing malladmin_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @malladmin_session %> |
<%= link_to 'Back', malladmin_sessions_path %>

app/views/malladmin_sessions/index.html.erb
<h1>Listing malladmin_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @malladmin_sessions.each do |malladmin_session| %>
  <tr>
    <td><%= malladmin_session.username %></td>
    <td><%= malladmin_session.password %></td>
    <td><%= malladmin_session.roll %></td>
    <td><%= link_to 'Show', malladmin_session %></td>
    <td><%= link_to 'Edit', edit_malladmin_session_path(malladmin_session) %></td>
    <td><%= link_to 'Destroy', malldmin_session, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_malladmin_session_path %>

app/views/malladmin_sessions/new.html.erb
<div style="color: black; background-color:white; height: 100%">

<h1> Login </h1>

<%= render 'form' %>

<%#= link_to 'Back', root_url %>
<br/>
<!--%#=  link_to 'Create New User', new_user_url %-->

</div>

app/views/malladmin_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @malladmin_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @malladmin_session.password %>
</p>
<p>
	<b>Roll:</b>
		<%= @malladmin_session.roll %>
<p/>

<%= link_to 'Edit', edit_malladmin_session_path(@malladmin_session) %> |
<%= link_to 'Back', malladmin_sessions_path %>